#
#
export FOX_REMOVE_AAPT=1
export FOX_REMOVE_BUSYBOX_BINARY=1
export FOX_USE_GREP_BINARY=0
export FOX_USE_XZ_UTILS=0
export FOX_USE_SED_BINARY=0
export FOX_USE_TAR_BINARY=0
export OF_FLASHLIGHT_ENABLE=1
export OF_NO_SAMSUNG_SPECIAL=1
export FOX_DRASTIC_SIZE_REDUCTION=1
export FOX_REMOVE_BASH=1
export FOX_REPLACE_BUSYBOX_PS=1
export OF_FL_PATH1="/sys/class/leds/mt-flash-led1"
export OF_FL_PATH1="/sys/class/leds/mt-flash-led2"
